org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,neoforge
mod_id=thief
archives_name=thief
mod_name=Thief
mod_version=1.2.5
mod_release_type=release
mod_license=GPLv3
maven_group=io.github.mortuusars.thief
mod_authors=mortuusars
mod_description=Stealing from villages has consequences.
mod_page=https://www.curseforge.com/minecraft/mc-mods/thief
mod_github=https://github.com/mortuusars/Thief
mod_issues=https://github.com/mortuusars/Thief/issues
mod_curseforge_project_id=839159
mod_modrinth_project_id=dGtSkt4t
# Minecraft properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
supported_minecraft_versions=26.1.2
# Fabric
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
fabric_supported_minecraft_versions=>=26.1
# NeoForge
neoforge_version=26.1.2.75
neoforge_version_range=[26.1,)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=26.1.3
required_forge_config_api_port_version=26.1
mixinextras_version=0.4.1
jupiterVersion=5.11.3
# Mod Versions
jei_version=29.6.2.31
lithostitched_fabric_version=1.6.4-fabric-26.1
lithostitched_neoforge_version=1.6.3-neoforge-26.1


