org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,neoforge
mod_id=thief
archives_name=thief
mod_name=Thief
mod_version=1.2.7
mod_release_type=release
mod_license=GPLv3
maven_group=io.github.mortuusars.thief
mod_authors=mortuusars
mod_description=Stealing from villages has consequences.
mod_page=https://www.curseforge.com/minecraft/mc-mods/thief
mod_github=https://github.com/mortuusars/Thief
mod_issues=https://github.com/mortuusars/Thief/issues
mod_curseforge_project_id=839159
mod_modrinth_project_id=dGtSkt4t
# Minecraft properties
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
supported_minecraft_versions=26.3
# Fabric
fabric_loader_version=0.18.5
fabric_api_version=0.152.1+26.3
fabric_supported_minecraft_versions=26.3.x
# NeoForge
neoforge_version=26.3.0.8-beta
neoforge_version_range=[26.3,26.4)
neoforge_loader_version_range=[4,)
# Dependencies
forge_config_api_port_version=26.3.1
required_forge_config_api_port_version=26.3
jupiterVersion=5.11.3
# Mod Versions
jei_version=31.4.0.22
jade_version=26.3.1
lithostitched_fabric_version=2.0.1-fabric-26.3
lithostitched_neoforge_version=2.0.1-neoforge-26.2


